"""
Django settings for napkin project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import environ
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# reading .env file
environ.Env.read_env()

GOOGLE_CLIENT_SECRET_FILE = {
  "type": "service_account",
  "project_id": "pythonsheets-321421",
  "private_key_id": "8d7f4d692a90bf59e5efa41550266e83acba44e9",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDDY9Eemv3OIf4j\nZUIOJ3qOnULauD7m/wUKjGb0HHtlgGEVuwwih8HpDgk38JbhkPwoZYAGICp8uNcD\n+/2WdQZU3OAtgm1XQzEEv9RGJoBH/0oTFuiYbQLJYH5QIHnwuaoymyETUQ/9b5X+\nHaYFUXUUgZpAY5Fg0aF0xFZnBzyZouKN7uxCq4EJ0AXdxtLhdXyb97hpUqxRvmG2\nyp977ksmgXbxFIvKFaRyYzbgiTddOhxBzbTGmsfmwBCQOz/4BJj0BrAw8Vh5tul4\n4QagMifT7zwRSWOzTRJL8vxdL7adQdaHfat4MlOC0rrSTmMCdSumb4yVlMBMc4Qr\n6F8VxG9XAgMBAAECggEAKjmhEL8oCGsaM+YHH23ys21S7FeS6HLGUSBEg47AMBBN\natfQaIn0Ivxwi5FH2hluFQDSaQB8jhWYCflkNSa3JpHRNKSSIqCXsFIQetSJNoX6\nKSPzQjWUu5ZJ1eEe2SIWoPcbb8Q982QxAwi/Pzj6V2MmxbF+0nCbNtPTZFKRCxZi\nT4zwgjNuCCCtBb3SnBgNX3qiNBzTC7TdAB7fxHlDgvivWFp2VxlZNuUEdjeDgK+6\nEUl6MQqt4/j3hr59sQKKetGOZz2faySffLNTNCfwPJXaTpll9FQO6QyxmBinRqOu\n3g4hlXaRfMJJi9xySdP+LD8h1X5DJwxF+NshrKRF2QKBgQD1ekFRsc/59SZDdhBw\njGY+XOQjKLy6GGgQKLAq+c1kE9KcAIYqy74P5yQQfxAXBsM8ci+VjUBthFkDmAR0\ntgDd4WvlnB2+pKAMhRflnhyrih46zKjZC8RrW2euM8h6I4BokT22IalRFy54A/RF\nX6IPicLrAHKbjjluduqSiWJMdQKBgQDLw+zwPXWY1rA1pT5SZDHUrV8ks8LFHdiq\nJGtl7vDpvm4/nkNRXcj/M6G1ObCfWVos2PiGmuzx1+T0NjGd1/+6LjR2ltm8DZeC\n7n41bKvUFqlsDG+6d+xeeVOtFCkM80//gjmHs2c1qG7Oj7QJmoqE/5qSkZtheGma\ns9Usn10DGwKBgQCmfk8DO9jVrgJPyyoHTBKkxZguiJjIl3ktTIt/+oHmGNPF300g\nhaPZYWpCjgu5smqE+uVvR6ilHxjIqTiMeE1KMHRf/WznOv0awMKeiIjlh/5M3za+\nT47fSdWef5y/yohzY985Qsd2KoTn/baVvvFKHKPJhDo3a1VkqN8cmHXFaQKBgHek\nAmrMq0+iPrRA4ebejaOiaErUgXfbnmvIFoczVKDp/zG7aytLNckiN8CArwPhIuFS\nRBpEvPsDGJuLdnaHbM+UcZlv2UhhcqSeA9y6gel1pOScKL4Dy/Vsp4ToYXIJKt+L\nRtw2qlMHIoiGN9+rrcmJiuikNed1HAyJqpEYwTQhAoGABAvlfzFwZdTlCXakrgkW\nrv9m+f5ZQBnjSk+LkQbV/xnapixd1z1D6cocR9RS4BIymbKMjc9MfvsaehVsqMlk\nxKIJqGgZpLwprzYajfNPmnd0andoi+43vhUA1qpCCmTibpMVGyyHR9osmtDFmCo9\n/sIvzLorH8okKyzLNm6RP3I=\n-----END PRIVATE KEY-----\n",
  "client_email": "python-sheets@pythonsheets-321421.iam.gserviceaccount.com",
  "client_id": "112313588562111372825",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/python-sheets%40pythonsheets-321421.iam.gserviceaccount.com"
}


import datetime
import os

from pathlib import Path

import os
from posixpath import abspath, dirname



PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+#q%-$2ph_+1886+2i(u8_lh=bh-6g)48rvo@c#uo8l+*6e@41'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ 'localhost', '127.0.0.1', '0.0.0.0', 'ec2-54-241-133-28.us-west-1.compute.amazonaws.com']
CORS_ALLOWED_ORIGINS = [ 'http://127.0.0.1:8000']


# Application definition
INSTALLED_APPS = [
    'corsheaders',
    'calculator.apps.CalculatorConfig',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
        #"rest_framework.permissions.IsAdminUser"
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_jwt.authentication.JSONWebTokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    "PAGE_SIZE": 10
}

JWT_AUTH = {
    'JWT_ALLOW_REFRESH': True,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(hours=1),
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'napkin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'napkin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'var/static_root/'
STATICFILES_DIRS = ['static']

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
